name: Package and Publish to NuGet

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PROJECT_FILE_PATH: 'Imperative.AutoDI/Imperative.AutoDI.csproj'
  PACKAGE_LOCK_FILE_PATH: 'Imperative.AutoDI/packages.lock.json'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7.0.0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5.3.0
        with:
          dotnet-version: '10.x'

      - name: .NET Restore (--locked-mode)
        run: dotnet restore --locked-mode

      - name: .NET Pack (--no-restore)
        run: dotnet pack ${{ env.PROJECT_FILE_PATH }} -c Release -o ${{ env.DOTNET_ROOT }}/mypackage -p:SourceRevisionId=${{ github.sha }} --no-restore

      - name: Publish to NuGet
        run: dotnet nuget push ${{ env.DOTNET_ROOT }}/mypackage/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
